/**
 * 100 distinct hero-image scene prompts for Essay Hub / FAL.
 * Hash-indexed by `heroSceneVariantIndex` so neighboring essays rarely repeat the same look.
 * Keep palette language compatible with SaaS navy / soft purple / warm wood (global suffix in `buildEssayHubHeroImagePrompt`).
 */

export const ESSAY_HERO_SCENE_VARIANTS: readonly string[] = [
  `Bright library aisle: young Black man in a navy hoodie skims a book beside a laptop on a wood table; candid three-quarter view, shallow depth of field.`,
  `Campus café: two young men (South Asian and White) lean over one laptop debating notes; laughter mid-sentence, documentary realism, not posed.`,
  `Engineering lab bench: East Asian man adjusts wires on a small kit while a printed checklist sits open—face concentrated, cool fluorescent + window mix.`,
  `Outdoor quad steps: Latino young man reads on a tablet, backpack at feet, trees and brick soft-blur background; late afternoon light.`,
  `Writing center: mature Black woman staff tutor points at a paragraph while a male student listens; whiteboard edge visible, collaborative—not lecture hall.`,
  `Dorm desk at night: warm desk lamp on young Arab man typing; mug and sticky notes, cozy navy bedding blur; intimate environmental portrait.`,
  `High school classroom (modern): male teacher in casual blazer gestures at projector while two students in front row take notes; shallow DOF on foreground student.`,
  `University hallway: professor with gray hair and young South Asian woman walk side by side with folders—candid corridor motion, glass and wood reflections.`,
  `Study group of four around a round table: mixed genders and ethnicities, one woman gestures, two men lean in, laptops open; teamwork energy.`,
  `Overhead shot: diverse hands—brown and light skin—pointing at one printed essay draft on wood grain; pens and highlighters; faces out of frame.`,
  `Athletic young Black woman in team jacket still opens laptop on bleachers; stadium soft blur; serious “student-athlete” vibe, not glamour shot.`,
  `Close profile: young White man with freckles and glasses reads printed feedback; window light on cheek; shallow depth, authentic skin texture.`,
  `Pair on campus bench: young man and woman (different builds) share earbuds reviewing audio notes on phone; trees bokeh; relaxed friendship.`,
  `Graduate student lounge: older Middle Eastern man (30s) stacks journal articles beside laptop; coffee ring on table—believable clutter.`,
  `Chemistry prep room: young Vietnamese woman in lab coat writes equations on small pad while male peer holds safety goggles; not a stock lab cliché.`,
  `Career services office: young Black man shakes hands with advisor across desk; laptop closed, folder open—professional but warm, not corporate headshot.`,
  `Library carrel: only hands and forearms visible—one pair darker, one lighter—passing a sticky note; tight candid detail.`,
  `Evening library: young Indian man in olive sweater under tall lamps; long exposure feel without blur—quiet focus, wood tables dominant.`,
  `Campus makerspace: two guys (Black and mixed-race) lean over 3D-printed model beside laptop; safety glasses on forehead; STEM pride without posing.`,
  `Seminar room: female TA at side whiteboard sketches outline while three students (mixed) face her; backs of chairs frame foreground.`,
  `Rainy window seat: young East Asian woman journals while droplets streak glass; laptop closed; contemplative palette, navy knit.`,
  `Outdoor picnic table: trio—two men, one woman—spread papers against wind clips; pine trees; collegiate casual layers.`,
  `Music building hallway: young man carries instrument case in one hand, phone with scholarship email in other; motion blur on passing students.`,
  `Disability-inclusive: young man in wheelchair at accessible-height desk with laptop; peer standing beside pointing at screen; respectful documentary tone.`,
  `Night class exit: young Hispanic couple walks under campus lamps comparing phones; brick arches; cinematic but natural color grading.`,
  `Science quad: young Black woman in green sweater photographs whiteboard notes with phone while male friend holds umbrella; overcast soft light.`,
  `Stacked books foreground blur: young White man peeks between shelves searching a call number; playful discovery, not stressed cramming.`,
  `Debate prep room: two young men face each other across table with timers and notecards; competitive but friendly; wood-paneled walls.`,
  `Art studio corner: young South Asian man critiques sketch on easel while laptop shows reference PDF; paint tubes blurred foreground.`,
  `Campus coffee cart: barista hands cup to young Filipino woman who balances laptop on other arm; steam and wood cart; slice-of-life.`,
  `Basement archive: young man pulls archive box while female archivist supervises; fluorescent + warm task light mix; research seriousness.`,
  `Rooftop garden study: two women (Black and East Asian) sit on concrete ledge with laptops; city haze soft; sustainable campus vibe.`,
  `Flipped classroom: students in small clusters; foreground young man explains tablet screen to peer; instructor blurred at back.`,
  `Language lab: young Middle Eastern woman wears headset speaking into mic while male classmate watches waveform on shared monitor.`,
  `Commuter lot: young man sits in driver seat with laptop on knees before class; steering wheel and backpack visible; real-life grind.`,
  `Parents’ weekend vibe: older couple listens while college-age son gestures at brochure on table—multigenerational, warm wood interior.`,
  `Studio apartment: young Nigerian man on video call with laptop; ring light subtle; sticky goal board behind—remote learner realness.`,
  `Campus chapel study nook: young woman reads in stained-glass colored light on bench; quiet spiritual campus corner, respectful.`,
  `Field station: two students in fleeces log data on rugged laptop outdoors; grass and sky bokeh; environmental major authenticity.`,
  `Student union booth: club fair blur; foreground Black male student signs interest sheet on clipboard while friend laughs.`,
  `Theater backstage: young man memorizes lines from paper under work light; cables and cases soft blur—performing arts major.`,
  `Co-working on floor: four students sit on carpet with laptops in circle like startup sprint; socks and backpacks—informal energy.`,
  `Professor office hours door ajar: young woman enters with folder; professor stands from desk; warm wood bookshelves frame.`,
  `Campus bridge: two international students compare translation apps on phones; river and railing lead lines; windy hair natural.`,
  `Microbiology window lab: young White woman pipettes while male partner records on tablet behind glass to viewer; clean science aesthetic.`,
  `Basketball court sideline: young Latino man in jersey ties shoe while textbook rests on bench; dusk sky; athlete-student duality.`,
  `Silent floor sign visible: young East Asian man winces smiling at loud whisper from friend—library humor candid.`,
  `Campus food hall: long table mixed group shares fries while one laptop open; overhead wide shot; busy but not chaotic.`,
  `Snow campus: young Black woman in puffer holds laptop bag; breath visible; footprints—seasonal variety without holiday kitsch.`,
  `Sunset silhouette: two friends high-five holding rolled papers; faces dark, rim light on hair; celebratory but not staged cheer.`,
  `Coding club: young South Asian man explains GitHub on projector to diverse seated students; neon strip lights very subtle in blur.`,
  `Nursing skills lab: young woman practices chart on tablet while peer in scrubs watches mannequin blurred—health major specificity.`,
  `Journalism newsroom: young Black man edits article on desktop with sticky editor notes; red accent only in blurred signage—not text readable.`,
  `Campus observatory dome interior: young man adjusts telescope laptop interface; dim blue instrument glow on face.`,
  `Fashion program studio: young man sketches on tablet with stylus; fabric bolts blurred; creative major, not runway glam.`,
  `Veterans lounge: older student veteran in plain tee reviews benefits PDF with younger peer pointing; respectful, muted tones.`,
  `Greenhouse: two botany students (woman and man) examine leaves with phone macro; humidity haze; STEM field authenticity.`,
  `Campus radio booth: young Hispanic woman speaks into mic while male engineer gives thumbs through glass; creative tech.`,
  `Architecture studio: huge paper model foreground; young East Asian man measures with ruler while laptop shows CAD; tilt-shift feel.`,
  `Philosophy seminar: circle of students on armchairs; bearded young man speaks while others lean forward; warm lamp light.`,
  `Campus gym study nook: young woman stretches hamstring on mat while flashcards beside laptop—wellness + academics mix.`,
  `Shuttle bus interior: young man balances laptop on knees during commute; window streaks; public transit student life.`,
  `Campus pond dock: two friends sit legs dangling; one holds closed laptop; reflection on water; calm editorial tone.`,
  `Debate trophy case hallway: young White woman practices speech gestures alone in mirror-like glass reflection; shallow DOF.`,
  `STEM poster session: young Black man explains trifold to two listeners holding coffee; busy conference blur—graduate fair energy.`,
  `Campus print shop: young South Asian woman collects bound thesis; staff hands package; industrial shelves soft blur.`,
  `Night security escort path: two students walk under lamps with laptops closed; safety-conscious campus vibe, not dramatic.`,
  `Campus child care window: young parent student waves to toddler inside while holding backpack and laptop—nontraditional student dignity.`,
  `Orchestra pit edge: young man highlights sheet music while laptop plays MIDI; velvet and brass bokeh.`,
  `Campus farm: young woman in boots records soil notes on rugged tablet; barn wood and sky; ag-school specificity.`,
  `Glass study cube: two men face each other through frosted partition silhouettes; modern architecture lines; corporate-edu hybrid.`,
  `Campus esports arena soft light: young teammates debrief on laptops after match; jerseys, no logos readable.`,
  `Scholarship workshop flyer table: young Latino staffer explains pamphlet to curious student; folding table and banners blurred—no readable text.`,
  `Campus map kiosk: two international students orient with phone map while holding paper schedules; midday sun.`,
  `Studio recording: young Black woman adjusts mic while male producer points at laptop waveform; creative collaboration.`,
  `Campus climbing wall soft background: young man chalks hands before laptop on bench—unique hobby + study juxtaposition.`,
  `Historic lecture hall: wooden seats; young East Asian man takes notes on tablet while sunbeam cuts across dust—timeless academic.`,
  `Campus bike rack: young woman locks bike while holding rolled poster and laptop bag; motion and errands realism.`,
  `Peer mentor match: older undergrad points campus map app on phone for first-year; smiling, backpacks; orientation energy.`,
  `Campus health center waiting: young man fills tablet form on knee; calm institutional interior; soft blues in seating.`,
  `Studio ceramics: young man wipes hands on apron while checking scholarship deadline on phone; clay blur foreground.`,
  `Campus observatory lawn: group lies on blanket with laptops closed discussing stars; night sky gradient—not cheesy astro stock.`,
  `Campus tunnel between buildings: two friends walk fast comparing quiz answers on phones; fluorescent rhythm; motion.`,
  `Deaf/HoH inclusive: two students sign at table with laptop open; respectful framing, clear hands, warm lighting.`,
  `Campus fashion swap meet blur: student tries jacket while friend holds laptop showing budget spreadsheet—quirky real college.`,
  `Glass engineering bridge: young South Asian woman leans on railing with laptop closed, thinking; city campus vista soft blur.`,
  `Campus therapy dog visit corner: young man pets dog while laptop nearby; stress relief humane moment, not gimmicky.`,
  `Night library stacks: young Black man on rolling ladder reaches book while phone flashlight—dramatic but believable practical light.`,
  `Campus river cleanup club: two students in gloves pause with tablet checklist; outdoor service learning; mud on boots subtle.`,
  `Grad school apartment kitchen: young couple (different ethnicities) split chores while one scrolls laptop financial aid page—domestic real.`,
  `Campus wind tunnel lab: young man holds model plane while peer reads laptop telemetry; specialized STEM, not generic lab.`,
  `Theater lobby: young woman reviews monologue on phone voice memo; velvet rope blur; arts major focus.`,
  `Campus startup incubator: young Middle Eastern man pitches to two seated mentors with laptops; whiteboard graphs blurred—no readable text.`,
  `Snowy bus stop shelter: young East Asian man warms hands with coffee steam; backpack and laptop case; winter commuter grit.`,
  `Campus botanical bench: young White woman presses leaves in notebook while male friend photographs with phone for project.`,
  `Night dorm common room: mixed group watches muted TV while one student alone edits essay on laptop—foreground isolation vs background social.`,
  `Campus gallery: young Black man sketches sculpture on tablet; artwork blurred on walls—no recognizable copyrighted pieces.`,
  `Athletic training room ice bath area: young woman reviews rehab schedule on tablet with trainer pointing—sports medicine student path.`,
  `Campus greenhouse atrium: sunlight through leaves on two students comparing data on one laptop; humid sparkle realism.`,
  `Finals week meme energy: young man facepalms smiling at laptop while friend offers candy—humor candid, not mocking.`,
  `Campus river bridge at blue hour: young South Asian woman closes laptop into bag; city lights bokeh; closure moment.`,
  `Inclusive faith group room: diverse students circle with notebooks; young man speaks while others listen; respectful neutral decor.`,
  `Campus 3D scan lab: young woman rotates artifact on turntable while male peer monitors laptop mesh—digital humanities vibe.`,
  `Scholarship ceremony rehearsal empty hall: young Latino man practices speech at podium with laptop on lectern; grand but quiet.`,
  `Campus food truck line: young Black woman balances laptop on one palm while scrolling phone with other—multitask chaos candid.`,
  `Sunrise track: young man jogs past bleachers carrying backpack and water; laptop implied in bag—discipline montage feel.`,
  `Campus makerspace sewing corner: young woman threads machine while tablet shows pattern; craft + tech crossover.`,
  `Night security desk: friendly guard points directions while international student shows phone map—helpful campus safety moment.`,
  `Campus rooftop solar panels: two engineering students kneel with meter and laptop; safety vests subtle; sustainability pride.`,
  `Library basement microfilm: young East Asian man loads reel while female librarian assists; retro research cinematic.`,
  `Campus meditation room: young woman breathes eyes closed on cushion; laptop closed beside—balance theme, not religious iconography.`,
  `Graduation practice cap toss prep: students in background blur; foreground young man tightens tie while reading phone reminder—anticipation.`,
  `Campus tunnel mural: colorful abstract wall blur; young Black woman walks with laptop bag—environmental diversity without faces repeated.`,
  `Peer code review: two young men side by side on stools with laptops back-to-back; animated explanation gesture; CS lab casual.`,
  `Campus observatory exit: young White man zips jacket while holding star chart print; Milky Way soft gradient sky—not fake NASA.`,
  `Final scene variety lock: wide aerial-from-balcony of campus quad with tiny figures studying on grass—human scale, epic but real photography.`
];

export const ESSAY_HERO_SCENE_VARIANT_COUNT = ESSAY_HERO_SCENE_VARIANTS.length;

/** Stable pseudo-random index 0..N-1 from essay ordinal + grant title. */
export function heroSceneVariantIndex(existingIndex: number, grantTitle: string): number {
  let h = 2166136261 >>> 0;
  const t = grantTitle.trim();
  for (let i = 0; i < t.length; i += 1) {
    h ^= t.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  const mix =
    (Math.imul(existingIndex, 0x9e3779b9) ^ h ^ Math.imul(existingIndex + 31, t.length + 1)) >>>
    0;
  return mix % ESSAY_HERO_SCENE_VARIANTS.length;
}
