import { NATIONWIDE_LOCATION } from '@/lib/scholarships/scholarshipCatalog';
import type { SeoCanonicalTag } from '@/lib/scholarships/seoTags/vocabulary';

export const SEO_ROUTE_STATE_SLUG_TO_LABEL: Record<string, string> = {
  alabama: 'Alabama',
  alaska: 'Alaska',
  arizona: 'Arizona',
  arkansas: 'Arkansas',
  california: 'California',
  colorado: 'Colorado',
  connecticut: 'Connecticut',
  delaware: 'Delaware',
  'district-of-columbia': 'District of Columbia',
  florida: 'Florida',
  georgia: 'Georgia',
  hawaii: 'Hawaii',
  idaho: 'Idaho',
  illinois: 'Illinois',
  indiana: 'Indiana',
  iowa: 'Iowa',
  kansas: 'Kansas',
  kentucky: 'Kentucky',
  louisiana: 'Louisiana',
  maine: 'Maine',
  maryland: 'Maryland',
  massachusetts: 'Massachusetts',
  michigan: 'Michigan',
  minnesota: 'Minnesota',
  mississippi: 'Mississippi',
  missouri: 'Missouri',
  montana: 'Montana',
  nebraska: 'Nebraska',
  nevada: 'Nevada',
  'new-hampshire': 'New Hampshire',
  'new-jersey': 'New Jersey',
  'new-mexico': 'New Mexico',
  'new-york': 'New York',
  'north-carolina': 'North Carolina',
  'north-dakota': 'North Dakota',
  ohio: 'Ohio',
  oklahoma: 'Oklahoma',
  oregon: 'Oregon',
  pennsylvania: 'Pennsylvania',
  'rhode-island': 'Rhode Island',
  'south-carolina': 'South Carolina',
  'south-dakota': 'South Dakota',
  tennessee: 'Tennessee',
  texas: 'Texas',
  utah: 'Utah',
  vermont: 'Vermont',
  virginia: 'Virginia',
  washington: 'Washington',
  'west-virginia': 'West Virginia',
  wisconsin: 'Wisconsin',
  wyoming: 'Wyoming',
  nationwide: NATIONWIDE_LOCATION
};

export const SEO_ROUTE_ELIGIBILITY_SEGMENTS: Record<string, string> = {
  'for-women': 'women',
  women: 'women',
  'international-students-eligibility': 'international_students',
  minority: 'minority',
  hispanic: 'hispanic',
  'african-american': 'african_american',
  'first-generation': 'first_generation',
  disability: 'disability',
  veterans: 'veterans',
  lgbtq: 'lgbtq',
  'single-parent': 'single_parent',
  'foster-youth': 'foster_youth',
  'native-american': 'native_american',
  'low-income': 'low_income',
  'financial-need': 'financial_need'
};

export const SEO_ROUTE_EDUCATION_SEGMENTS: Record<string, string> = {
  'high-school-senior': 'high_school_senior',
  graduate: 'graduate',
  phd: 'phd',
  'community-college': 'community_college',
  'trade-school': 'trade_school',
  mba: 'graduate'
};

export const SEO_ROUTE_EASY_APPLY_SEGMENTS: Record<string, string> = {
  'no-essay': 'no_essay',
  'easy-apply': 'easy_apply',
  'quick-apply': 'quick_apply',
  'few-requirements': 'few_requirements'
};

export const SEO_ROUTE_GPA_SEGMENTS: Record<string, string> = {
  'no-gpa-requirement': 'gpa_none',
  'gpa-2-0': 'gpa_2',
  'gpa-2-5': 'gpa_25',
  'gpa-3-0': 'gpa_3',
  'gpa-3-5': 'gpa_35'
};

export const SEO_ROUTE_SEGMENT_TO_CANONICAL_TAG: Record<string, SeoCanonicalTag> = {
  'for-women': 'women',
  women: 'women',
  'international-students': 'international_students',
  'international-students-eligibility': 'international_students',
  minority: 'minority',
  hispanic: 'hispanic',
  'african-american': 'african_american',
  'first-generation': 'first_generation',
  disability: 'disability',
  veterans: 'veterans',
  lgbtq: 'lgbtq',
  'single-parent': 'single_parent',
  'foster-youth': 'foster_youth',
  'native-american': 'native_american',
  'low-income': 'low_income',
  'financial-need': 'financial_need',
  'high-school': 'high_school',
  'high-school-senior': 'high_school_senior',
  undergraduate: 'undergraduate',
  graduate: 'graduate',
  phd: 'phd',
  mba: 'graduate',
  'community-college': 'community_college',
  'trade-school': 'trade_school',
  engineering: 'engineering',
  'computer-science': 'computer_science',
  stem: 'stem',
  'no-essay': 'no_essay',
  'easy-apply': 'easy_apply',
  'quick-apply': 'quick_apply',
  'few-requirements': 'few_requirements',
  'no-gpa-requirement': 'no_gpa_requirement',
  'gpa-2-0': 'gpa_2_0',
  'gpa-2-5': 'gpa_2_5',
  'gpa-3-0': 'gpa_3_0',
  'gpa-3-5': 'gpa_3_5',
  'closing-soon': 'closing_soon',
  'under-5000': 'under_5000',
  'under-10000': 'under_10000',
  verified: 'verified_source',
  'verified-source': 'verified_source',
  'payout-college': 'payout_college',
  'payout-student': 'payout_student',
  'payout-non-monetary': 'payout_non_monetary',
  'payout-not-stated': 'payout_not_stated'
};
