#!/usr/bin/env bash
# Refresh shadow-api.env legacy anon/service JWT keys (keeps basic-auth password).
set -euo pipefail

ROOT="${SCHOLARSHIPTOP_ROOT:-/opt/scholarshiptop}"
SHADOW_ENV="${ROOT}/env/shadow-api.env"
ANON_FILE="/root/.supabase-legacy-anon-jwt"
SERVICE_FILE="/root/.supabase-legacy-service-jwt"

if [[ ! -f "${SHADOW_ENV}" ]]; then
  echo "ERROR: ${SHADOW_ENV} missing — run setup-shadow-supabase-api-nginx.sh --apply first" >&2
  exit 1
fi
if [[ ! -s "${ANON_FILE}" || ! -s "${SERVICE_FILE}" ]]; then
  echo "ERROR: production legacy JWT files missing — run generate-legacy-supabase-jwt.sh" >&2
  exit 1
fi

# shellcheck disable=SC1090
source "${SHADOW_ENV}"

USER="${SHADOW_API_BASIC_AUTH_USER:?}"
PASS="${SHADOW_API_BASIC_AUTH_PASS:?}"
URL="${SHADOW_SUPABASE_URL:-https://scholarshiptop.com/vps-shadow-supabase-4c}"
ANON_VAL="$(tr -d '\r\n' < "${ANON_FILE}")"
SERVICE_VAL="$(tr -d '\r\n' < "${SERVICE_FILE}")"

umask 077
cat > "${SHADOW_ENV}" <<EOF
# Generated by refresh-shadow-api-jwt-keys.sh — DO NOT COMMIT
SHADOW_SUPABASE_URL=${URL}
SHADOW_API_BASIC_AUTH_USER=${USER}
SHADOW_API_BASIC_AUTH_PASS=${PASS}
SHADOW_SUPABASE_ANON_KEY='${ANON_VAL}'
SHADOW_SUPABASE_SERVICE_ROLE_KEY='${SERVICE_VAL}'
EOF
chmod 600 "${SHADOW_ENV}"
echo "[refresh-shadow-jwt] Updated ${SHADOW_ENV} with production legacy JWT files (values not printed)"
