#!/usr/bin/env bash
# Stage 4C — Enable public shadow Supabase API route on production nginx (NOT cutover).
set -euo pipefail

ROOT="${SCHOLARSHIPTOP_ROOT:-/opt/scholarshiptop}"
APP="${ROOT}/app"
NGINX_INCLUDES="${ROOT}/nginx/includes"
NGINX_CONF="${ROOT}/nginx/conf.d/scholarshiptop-site.conf"
SECRETS="${ROOT}/secrets"
SHADOW_INCLUDE_SRC="${APP}/ops/vps/nginx/includes/scholarshiptop-shadow-supabase-api.conf.example"
SHADOW_INCLUDE_DST="${NGINX_INCLUDES}/scholarshiptop-shadow-supabase-api.conf"
SHADOW_ENV="${ROOT}/env/shadow-api.env"
HTPASSWD="${NGINX_INCLUDES}/shadow-api.htpasswd"
MODE="${1:---dry-run}"
SHADOW_USER="${SHADOW_API_BASIC_AUTH_USER:-shadow-smoke}"

log() { echo "[setup-shadow-api] $*"; }

generate_password() {
  openssl rand -base64 24 | tr -d '/+=' | head -c 32
}

ensure_site_conf_include() {
  local marker="scholarshiptop-shadow-supabase-api.conf"
  if grep -q "${marker}" "${NGINX_CONF}" 2>/dev/null; then
    log "site.conf already includes shadow API"
    return 0
  fi
  if [[ "${MODE}" == "--dry-run" ]]; then
    log "DRY-RUN: would add include ${marker} before proxy-locations in ${NGINX_CONF}"
    return 0
  fi
  sed -i "s|include /etc/nginx/includes/scholarshiptop-proxy-locations.conf;|include /etc/nginx/includes/scholarshiptop-shadow-supabase-api.conf;\\n  include /etc/nginx/includes/scholarshiptop-proxy-locations.conf;|" \
    "${NGINX_CONF}"
  log "Added shadow include to ${NGINX_CONF}"
}

setup_htpasswd() {
  local pass="$1"
  if [[ "${MODE}" == "--dry-run" ]]; then
    log "DRY-RUN: would write ${HTPASSWD} for user ${SHADOW_USER}"
    return 0
  fi
  mkdir -p "${SECRETS}"
  if command -v htpasswd >/dev/null 2>&1; then
    htpasswd -bc "${HTPASSWD}" "${SHADOW_USER}" "${pass}" >/dev/null
  else
    docker run --rm httpd:2.4-alpine htpasswd -nbB "${SHADOW_USER}" "${pass}" > "${HTPASSWD}"
  fi
  chmod 644 "${HTPASSWD}"
  log "Wrote ${HTPASSWD} (mode 644 for nginx read inside container)"
}

write_shadow_env() {
  local pass="$1"
  local anon_file="/root/.supabase-legacy-anon-jwt"
  local service_file="/root/.supabase-legacy-service-jwt"
  if [[ ! -f "${anon_file}" ]]; then
    anon_file="/root/.supabase-legacy-anon-jwt-internal"
  fi
  if [[ ! -f "${service_file}" ]]; then
    service_file="/root/.supabase-legacy-service-jwt-internal"
  fi
  if [[ ! -f "${anon_file}" ]]; then
    echo "ERROR: legacy anon JWT file missing — run generate-legacy-supabase-jwt.sh" >&2
    exit 1
  fi
  if [[ "${MODE}" == "--dry-run" ]]; then
    log "DRY-RUN: would write ${SHADOW_ENV}"
    return 0
  fi
  umask 077
  ANON_VAL="$(tr -d '\r\n' < "${anon_file}")"
  SERVICE_VAL="$(tr -d '\r\n' < "${service_file}")"
  cat > "${SHADOW_ENV}" <<EOF
# Generated by setup-shadow-supabase-api-nginx.sh — DO NOT COMMIT
SHADOW_SUPABASE_URL=https://scholarshiptop.com/vps-shadow-supabase-4c
SHADOW_API_BASIC_AUTH_USER=${SHADOW_USER}
SHADOW_API_BASIC_AUTH_PASS=${pass}
SHADOW_SUPABASE_ANON_KEY='${ANON_VAL}'
SHADOW_SUPABASE_SERVICE_ROLE_KEY='${SERVICE_VAL}'
EOF
  chmod 600 "${SHADOW_ENV}"
  log "Wrote ${SHADOW_ENV} (chmod 600)"
}

reload_nginx() {
  if [[ "${MODE}" == "--dry-run" ]]; then
    log "DRY-RUN: would reload scholarshiptop-nginx"
    return 0
  fi
  cp "${SHADOW_INCLUDE_SRC}" "${SHADOW_INCLUDE_DST}"
  docker network connect scholarshiptop-supabase-api_supabase_api_test scholarshiptop-nginx 2>/dev/null || true
  docker exec scholarshiptop-nginx nginx -t
  docker exec scholarshiptop-nginx nginx -s reload
  log "nginx reloaded"
}

case "${MODE}" in
  --dry-run|--apply) ;;
  *) echo "Usage: $0 --dry-run|--apply" >&2; exit 1 ;;
esac

PASS="$(generate_password)"
ensure_site_conf_include
setup_htpasswd "${PASS}"
write_shadow_env "${PASS}"
reload_nginx

if [[ "${MODE}" == "--dry-run" ]]; then
  echo "STAGE_4C_SHADOW_SETUP_DRY_RUN_OK"
else
  echo "STAGE_4C_SHADOW_SETUP_APPLIED"
fi
