#!/usr/bin/env bash
# Stage 1 — Install and harden PostgreSQL on VPS for scholarshiptop_prod.
# Run on VPS as root. Does NOT touch Supabase. Does NOT migrate data.
#
# Usage:
#   sudo bash ops/vps/scripts/setup-postgres.sh
#
# Prerequisites:
#   - Ubuntu/Debian VPS with apt
#   - Set POSTGRES_APP_PASSWORD before run (or script generates one to /root/.scholarshiptop-db-init)

set -euo pipefail

POSTGRES_DB="${POSTGRES_DB:-scholarshiptop_prod}"
POSTGRES_USER="${POSTGRES_USER:-scholarshiptop_app}"
BACKUP_DIR="${POSTGRES_BACKUP_DIR:-/opt/scholarshiptop-db-backups}"
ENV_DIR="${SCHOLARSHIPTOP_ROOT:-/opt/scholarshiptop}/env"
INIT_SECRET="/root/.scholarshiptop-db-init"

echo "[setup-postgres] Stage 1 — VPS PostgreSQL setup (no data migration)"

if ! command -v psql >/dev/null 2>&1; then
  echo "[setup-postgres] Installing postgresql..."
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -qq
  apt-get install -y postgresql postgresql-contrib
fi

PG_VERSION="$(psql --version | grep -oE '[0-9]+' | head -1)"
echo "[setup-postgres] PostgreSQL version: ${PG_VERSION}"

systemctl enable postgresql
systemctl start postgresql

# Restrict listen to localhost
PG_CONF="$(find /etc/postgresql -name postgresql.conf 2>/dev/null | head -1)"
PG_HBA="$(find /etc/postgresql -name pg_hba.conf 2>/dev/null | head -1)"

if [[ -n "${PG_CONF}" ]]; then
  if grep -q "^listen_addresses" "${PG_CONF}"; then
    sed -i "s/^listen_addresses.*/listen_addresses = 'localhost'/" "${PG_CONF}"
  else
    echo "listen_addresses = 'localhost'" >> "${PG_CONF}"
  fi
fi

if [[ -n "${PG_HBA}" ]]; then
  # Remove open remote lines if any (keep local socket + 127.0.0.1)
  grep -v '^host.*all.*all.*0\.0\.0\.0' "${PG_HBA}" > "${PG_HBA}.tmp" || true
  mv "${PG_HBA}.tmp" "${PG_HBA}"
  if ! grep -q '127.0.0.1/32.*scram-sha-256' "${PG_HBA}"; then
    echo "host    ${POSTGRES_DB}    ${POSTGRES_USER}    127.0.0.1/32    scram-sha-256" >> "${PG_HBA}"
  fi
fi

systemctl reload postgresql

# App password
if [[ -z "${POSTGRES_APP_PASSWORD:-}" ]]; then
  if [[ -f "${INIT_SECRET}" ]]; then
    # shellcheck disable=SC1090
    source "${INIT_SECRET}"
  else
    POSTGRES_APP_PASSWORD="$(openssl rand -base64 32 | tr -d '/+=' | head -c 32)"
    umask 077
    cat > "${INIT_SECRET}" <<EOF
# Generated $(date -u +%Y-%m-%dT%H:%M:%SZ) — chmod 600, do not commit
POSTGRES_APP_PASSWORD='${POSTGRES_APP_PASSWORD}'
POSTGRES_DB='${POSTGRES_DB}'
POSTGRES_USER='${POSTGRES_USER}'
EOF
    chmod 600 "${INIT_SECRET}"
    echo "[setup-postgres] Generated app password saved to ${INIT_SECRET} (not printed)"
  fi
fi

sudo -u postgres psql -v ON_ERROR_STOP=1 <<SQL
SELECT 'CREATE DATABASE ${POSTGRES_DB}' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${POSTGRES_DB}')\gexec
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${POSTGRES_USER}') THEN
    CREATE ROLE ${POSTGRES_USER} LOGIN PASSWORD '${POSTGRES_APP_PASSWORD}';
  END IF;
END\$\$;
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_USER};
SQL

sudo -u postgres psql -d "${POSTGRES_DB}" -v ON_ERROR_STOP=1 <<SQL
GRANT USAGE ON SCHEMA public TO ${POSTGRES_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${POSTGRES_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO ${POSTGRES_USER};
SQL

mkdir -p "${BACKUP_DIR}"
chmod 700 "${BACKUP_DIR}"

# Install backup cron if not present
BACKUP_SCRIPT="${SCHOLARSHIPTOP_ROOT:-/opt/scholarshiptop}/scripts/backup-postgres-daily.sh"
if [[ -f "${BACKUP_SCRIPT}" ]]; then
  CRON_LINE="15 3 * * * root ${BACKUP_SCRIPT} >> /var/log/scholarshiptop-pg-backup.log 2>&1"
  if ! grep -qF "backup-postgres-daily.sh" /etc/cron.d/scholarshiptop-postgres 2>/dev/null; then
    echo "${CRON_LINE}" > /etc/cron.d/scholarshiptop-postgres
    chmod 644 /etc/cron.d/scholarshiptop-postgres
    echo "[setup-postgres] Installed daily backup cron (03:15 UTC)"
  fi
fi

mkdir -p "${ENV_DIR}"
if [[ ! -f "${ENV_DIR}/postgres.env" ]]; then
  cat > "${ENV_DIR}/postgres.env" <<EOF
# Generated by setup-postgres.sh — set DATABASE_URL manually from ${INIT_SECRET}
DATABASE_URL=postgresql://${POSTGRES_USER}:REPLACE_FROM_${INIT_SECRET}@127.0.0.1:5432/${POSTGRES_DB}
DB_PROVIDER=supabase
POSTGRES_DB=${POSTGRES_DB}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_BACKUP_DIR=${BACKUP_DIR}
POSTGRES_BACKUP_RETENTION_DAYS=14
EOF
  chmod 600 "${ENV_DIR}/postgres.env"
  echo "[setup-postgres] Template env: ${ENV_DIR}/postgres.env (fill DATABASE_URL from init secret)"
fi

echo "[setup-postgres] DONE — database ${POSTGRES_DB}, user ${POSTGRES_USER}, backups ${BACKUP_DIR}"
echo "[setup-postgres] Port 5432 bound to localhost only. Supabase unchanged."
