/**
 * ES/FR completion sprint — route inventory CSV + MD.
 * Usage: npx tsx scripts/i18n-completion-inventory.ts
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  STAGE2_PILOT_CANONICAL_PATHS,
  STAGE2_PILOT_LOCALES
} from '../lib/i18n/pilotRoutes';
import {
  availableLocalesForPilotPath,
  listLocalizedPilotPages
} from '../lib/i18n/staticTranslations';

const DATE = '2026-05-20';
const OUT_DIR = join(process.cwd(), 'reports/seo');

type Row = {
  routeGroup: string;
  route: string;
  enExists: string;
  esExists: string;
  frExists: string;
  translatedUi: string;
  partialUi: string;
  indexPolicy: string;
  inSitemap: string;
  languageSwitcher: string;
  localeLinks: string;
  sameTemplate: string;
  risk: string;
  ready: string;
  notes: string;
};

const rows: Row[] = [];

function pushPilotStatics() {
  for (const path of STAGE2_PILOT_CANONICAL_PATHS) {
    const locales = availableLocalesForPilotPath(path);
    rows.push({
      routeGroup: 'Public/static SEO (pilot)',
      route: path,
      enExists: 'yes',
      esExists: locales.includes('es') ? 'yes' : 'no',
      frExists: locales.includes('fr') ? 'yes' : 'no',
      translatedUi: locales.length === 2 ? 'yes' : 'partial',
      partialUi: path === '/resources' ? 'no DB grid on ES/FR' : '',
      indexPolicy: 'index',
      inSitemap: 'yes (locale-es/fr buckets)',
      languageSwitcher: 'yes',
      localeLinks: '0 blocking (audited)',
      sameTemplate: 'yes',
      risk: 'low',
      ready: 'yes',
      notes: ''
    });
  }
}

function pushRoute(
  group: string,
  route: string,
  partial: Partial<Row>
) {
  rows.push({
    routeGroup: group,
    route,
    enExists: 'yes',
    esExists: partial.esExists ?? 'no',
    frExists: partial.frExists ?? 'no',
    translatedUi: partial.translatedUi ?? 'no',
    partialUi: partial.partialUi ?? '',
    indexPolicy: partial.indexPolicy ?? 'varies',
    inSitemap: partial.inSitemap ?? 'no',
    languageSwitcher: partial.languageSwitcher ?? 'no',
    localeLinks: partial.localeLinks ?? 'n/a',
    sameTemplate: partial.sameTemplate ?? 'yes',
    risk: partial.risk ?? 'medium',
    ready: partial.ready ?? 'no',
    notes: partial.notes ?? ''
  });
}

pushPilotStatics();

pushRoute('Funnel', '/get-scholarships', {
  esExists: 'yes',
  frExists: 'yes',
  translatedUi: 'yes',
  indexPolicy: 'noindex,follow',
  inSitemap: 'no',
  sameTemplate: 'yes',
  risk: 'low',
  ready: 'yes'
});
pushRoute('Funnel', '/signin', {
  esExists: 'yes',
  frExists: 'yes',
  translatedUi: 'yes',
  indexPolicy: 'noindex,follow',
  inSitemap: 'no',
  ready: 'yes',
  risk: 'low'
});
pushRoute('Funnel', '/subscription', {
  esExists: 'yes',
  frExists: 'yes',
  translatedUi: 'yes',
  indexPolicy: 'index (not in sitemap)',
  languageSwitcher: 'yes',
  ready: 'yes',
  notes: 'Lemon checkout EN by design'
});
pushRoute('Funnel', '/signup', {
  esExists: 'redirect',
  frExists: 'redirect',
  translatedUi: 'no',
  notes: '→ /onboarding EN'
});
pushRoute('Private', '/account', {
  esExists: 'yes (/es/account)',
  frExists: 'yes (/fr/account)',
  translatedUi: 'partial',
  partialUi: 'profile form mostly EN',
  indexPolicy: 'noindex,follow',
  ready: 'partial',
  notes: 'nav/back localized; form Stage 3M'
});
pushRoute('Private', '/onboarding', {
  translatedUi: 'partial',
  indexPolicy: 'noindex',
  ready: 'partial',
  risk: 'medium',
  notes: 'EN only route; shared copy fragments'
});
pushRoute('Private', '/essay', {
  translatedUi: 'no',
  indexPolicy: 'noindex',
  ready: 'no',
  notes: 'product EN — later'
});
pushRoute('DB SEO', '/scholarships/[slug]', {
  translatedUi: 'no',
  indexPolicy: 'index EN only',
  inSitemap: 'EN only',
  ready: 'no',
  notes: 'Zone C links allowed'
});
pushRoute('DB SEO', '/providers/[id]', {
  translatedUi: 'no',
  ready: 'no'
});
pushRoute('DB SEO', '/resources/[slug] CMS', {
  translatedUi: 'no',
  ready: 'no'
});

const md = `# ES/FR completion current inventory (${DATE})

Generated by \`scripts/i18n-completion-inventory.ts\`.

## Summary

| Metric | Value |
| --- | ---: |
| Pilot canonical paths | ${STAGE2_PILOT_CANONICAL_PATHS.length} |
| Localized pilot URLs (ES+FR) | ${listLocalizedPilotPages().length} |
| ES URLs | ${listLocalizedPilotPages({ locale: 'es' }).length} |
| FR URLs | ${listLocalizedPilotPages({ locale: 'fr' }).length} |

## Route table

| Group | Route | EN | ES | FR | UI | Ready | Index | Sitemap | Notes |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
${rows
  .map(
    (r) =>
      `| ${r.routeGroup} | ${r.route} | ${r.enExists} | ${r.esExists} | ${r.frExists} | ${r.translatedUi} | ${r.ready} | ${r.indexPolicy} | ${r.inSitemap} | ${r.notes || r.partialUi} |`
  )
  .join('\n')}

`;

const csvHeader =
  'routeGroup,route,enExists,esExists,frExists,translatedUi,partialUi,indexPolicy,inSitemap,languageSwitcher,localeLinks,sameTemplate,risk,ready,notes\n';
const csv =
  csvHeader +
  rows
    .map((r) =>
      [
        r.routeGroup,
        r.route,
        r.enExists,
        r.esExists,
        r.frExists,
        r.translatedUi,
        r.partialUi,
        r.indexPolicy,
        r.inSitemap,
        r.languageSwitcher,
        r.localeLinks,
        r.sameTemplate,
        r.risk,
        r.ready,
        r.notes
      ]
        .map((c) => `"${String(c).replace(/"/g, '""')}"`)
        .join(',')
    )
    .join('\n');

mkdirSync(OUT_DIR, { recursive: true });
const base = `i18n-es-fr-completion-current-inventory-${DATE}`;
writeFileSync(join(OUT_DIR, `${base}.md`), md, 'utf8');
writeFileSync(join(OUT_DIR, `${base}.csv`), csv, 'utf8');
console.log(`Wrote ${base}.md and .csv (${rows.length} rows)`);
