/**
 * Build services/content-hub/.env from root .env.local (never logs secret values).
 */
import fs from 'node:fs';
import path from 'node:path';

const ROOT_ENV = path.join(process.cwd(), '.env.local');
const OUT_ENV = path.join(process.cwd(), 'services/content-hub/.env');

function parseEnvFile(content: string): Map<string, string> {
  const map = new Map<string, string>();
  for (const line of content.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq <= 0) continue;
    const key = trimmed.slice(0, eq).trim();
    let val = trimmed.slice(eq + 1).trim();
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    map.set(key, val);
  }
  return map;
}

function main() {
  if (!fs.existsSync(ROOT_ENV)) {
    throw new Error('.env.local not found at repo root');
  }
  const src = parseEnvFile(fs.readFileSync(ROOT_ENV, 'utf8'));

  const openaiKey = src.get('OPENAI_API_KEY');
  const serviceKey = src.get('SUPABASE_SERVICE_ROLE_KEY');
  const supabaseUrl =
    src.get('SUPABASE_URL')?.trim() || src.get('NEXT_PUBLIC_SUPABASE_URL')?.trim();
  const siteUrl =
    src.get('SITE_URL')?.trim() || 'https://scholarshiptop.com';

  const missing: string[] = [];
  if (!openaiKey) missing.push('OPENAI_API_KEY');
  if (!serviceKey) missing.push('SUPABASE_SERVICE_ROLE_KEY');
  if (!supabaseUrl) missing.push('SUPABASE_URL or NEXT_PUBLIC_SUPABASE_URL');

  if (missing.length > 0) {
    throw new Error(`Missing in .env.local: ${missing.join(', ')}`);
  }

  const lines = [
    '# Generated by scripts/sync-content-hub-env.ts — do not commit',
    `OPENAI_API_KEY=${openaiKey}`,
    `SUPABASE_URL=${supabaseUrl}`,
    `SUPABASE_SERVICE_ROLE_KEY=${serviceKey}`,
    `SITE_URL=${siteUrl}`,
    'OPENAI_MODEL_STANDARD=gpt-5.5',
    'OPENAI_MODEL_SMART=gpt-5.5',
    'CONTENT_HUB_AUTO_PUBLISH=0',
    'CONTENT_HUB_POSTS_PER_RUN=1',
    'CONTENT_HUB_BATCH_LIMIT=1',
    'CONTENT_HUB_SOURCE=ai-resources-2026-05-21',
    '# CONTENT_HUB_ALLOW_PRODUCTION_WRITES=1  # set only when explicitly approved'
  ];

  fs.mkdirSync(path.dirname(OUT_ENV), { recursive: true });
  fs.writeFileSync(OUT_ENV, `${lines.join('\n')}\n`, 'utf8');
  console.log(
    JSON.stringify(
      {
        ok: true,
        wrote: 'services/content-hub/.env',
        keysWritten: lines
          .filter((l) => l.includes('=') && !l.startsWith('#'))
          .map((l) => l.split('=')[0]),
        contentHubAllowProductionWrites: false
      },
      null,
      2
    )
  );
}

main();
